### ISSUE TITLE
Problem on mavericks 

### ISSUE THREAD

**Issue by ckapfer** [frobware/cmd-key-happy#17]
There seems to be a bug with the latest version installed on mavericks 10.9.5.  cmd-key-happy seems to work with the exception that when cmd-w is removed from the exclusion list for Terminal in the .cmd-key-happy.lua file, this exclusion is not respected.  

Normal mac behavior dictates that cmd-w closes a tab ... after cmd-key-happy-restart, cmd-w still prompts to close the tab.  This poses problems in emacs -nw when trying to copy a region, M-w is copy region by default.

I reinstalled my old binaries that were compiled under snow leopard (recompiling the old version under mavericks failed).  The old previously compiled version seems to respect the exclusion and works okay!  Not sure about version info but the tar ball was called aim-stuff-cmd-key-happy-a456aa9.tar.gz ...

**Comment by frobware** [comment]
@ckapfer I'm going to close this. I haven't heard back in a while and ... hope it is working for you now.
