### ISSUE TITLE
possible issue with JDK 1.8 applications

### ISSUE THREAD

**Issue by jmcmichael** [frobware/cmd-key-happy#19]
I use IntelliJ with cmd-key-happy to better emulate emacs keybindings. It's been working fine, but due to some display issues with Apple's JDK, they're moving to a customized version of the 1.8 JDK.

When I try out their early release versions[1], cmd-key-happy ceases to work. I thought this might be because the name had changed, or they were booting up the app differently. But I got the version of IntelliJ that works with cmd-key-happy to do the exact same thing by forcing it to use a pkg installed version of the 1.8 JDK. 

So it looks to me like the new JDK 1.8 is the culprit, and it doesn't work well with cmd-key-happy.

Do you have any ideas what's going on?

Thanks for working on this project, nothing else does what it does and I depend on it daily.

[1] https://confluence.jetbrains.com/display/IDEADEV/IDEA+14.1+EAP specifically https://download.jetbrains.com/idea/ideaIU-140.2110.5-custom-jdk-bundled.dmg

**Comment by ghost** [comment]
I will take a look but last time I used IntelliJ it had an internal option
of switching to Emacs key bindings. I used this and it was mostly
tolerable. It's better on Linux as most of their supplied key bindings work
as you would expect, but on OS X you have to fiddle a bit more as some
clash with the Mac's notion of what should happen. For example, I think
Cmd-backspace in IntelliJ does not do kill-backword-word.

I also note that applications like Xamarin don't work with cmd-key-happy
either. I'm guessing some apps incessantly choose to do their own thing
rather than use the platforms key handling, which can also be a general
accessibility nightmare - the very same mechanism that cmd-key-happy uses.

On 3 Feb 2015, at 20:51, Joshua McMichael notifications@github.com wrote:

I use IntelliJ with cmd-key-happy to better emulate emacs keybindings. It's
been working fine, but due to some display issues with Apple's JDK, they're
moving to a customized version of the 1.8 JDK.

When I try out their early release versions[1], cmd-key-happy ceases to
work. I thought this might be because the name had changed, or they were
booting up the app differently. But I got the version of IntelliJ that
works with cmd-key-happy to do the exact same thing by forcing it to use a
pkg installed version of the 1.8 JDK.

So it looks to me like the new JDK 1.8 is the culprit, and it doesn't work
well with cmd-key-happy.

Do you have any ideas what's going on?

Thanks for working on this project, nothing else does what it does and I
depend on it daily.

[1] https://confluence.jetbrains.com/display/IDEADEV/IDEA+14.1+EAP
specifically
https://download.jetbrains.com/idea/ideaIU-140.2110.5-custom-jdk-bundled.dmg

—
Reply to this email directly or view it on GitHub
https://github.com/andymcd/cmd-key-happy/issues/19.

**Comment by jmcmichael** [comment]
Yeah, I chose IntelliJ b/c its emacs keybindings seemed to be the best of the modern IDEs.

To clarify: cmd-key-happy has been working fine with IntelliJ all the way up to the current release. It's only when its running on the v1.8 VM (when I use their early-release EAP, or force the release version to use 1.8\* instead of 1.6+ by modifying its config plist) that cmd-key-happy ceases to work with it.

So I don't think it's an issue with IntelliJ (as the exact same version of IntelliJ behaves differently with different VMs), but with the VM. Or the way that Apple JVM integrates with the OS vs the Oracle release.

**Comment by frobware** [comment]
I understand that it used to work; what I'm wary of is if it is doing its own thing in terms of key handling -- which is why I mentioned Xamarin as it looks like a native app but it too seemed to override whatever path cmd-key-happy was able to intercept. I have an hour free and will try it out now...

**Comment by ghost** [comment]
Are you running 10.10.2?

**Comment by ghost** [comment]
Would you mind sharing your .cmd-key-happy.lua file?

**Comment by jmcmichael** [comment]
@andymcd Sure, I've pasted it in below. You can see I tried every variation of IntelliJ's name I could find.
@frobware I believe I'm using the latest version, but I couldn't find where the version was specified in the code - I just got a new iMac and downloaded/compiled cmd-key-happy not more than two weeks ago.

``` lua
function Set(t)
   local s = {}
   for _,v in pairs(t) do s[v] = true end
   return s
end

function set_contains(t, e)
   return t[e]
end

-- The set of global shortcuts we don't want to swap cmd/alt.

global_excludes = Set{ "shift-cmd-tab",
                       "cmd-tab"}


-- The set of apps we want to consider swapping keys for, with some
-- notable exclusions. The exclusion means that a "cmd-w" will do the
-- normal OS Terminal behaviour. If you omit items then you would
-- have to use "alt-w" to close a terminal window.

apps = {
   Terminal = { exclude = Set{ "shift-cmd-[",
                               "shift-cmd-]",
                               "cmd-c",
                               "cmd-v",
                               "cmd-w",
                               "cmd-1",
                               "cmd-2",
                               "cmd-3",
                               "cmd-t",
                               "cmd-n",
                               "cmd-`",
                         } },
   Eclipse  = { exclude = {} },
   Xcode    = { exclude = {} },
   ["iTerm"] = { exclude = {} },
   ["LightTable"] = { exclude = {} },
   ["WebStorm"] = { exclude = {} },
   ["java"] = { exclude = {} },
   ["IntelliJ IDEA"] = { exclude = {} },
   ["IntelliJ IDEA 14"] = { exclude = {} },
   ["IntelliJIdea14"] = { exclude = {} },
   ["IntelliJ IDEA 14 EAP"] = { exclude = {} },
   ["Parallels Desktop"] = {},
}

-- Return true to swap cmd/alt, otherwise false.

-- This function is passed a table comprising the following keys:
--
--   key_str_seq        key sequence (e.g., "shift-cmd-e")
--   alt                true if the alt key was pressed
--   fn                 true if the fn key was pressed
--   control            true if the control key was pressed
--   shift              true if the shift key was pressed
--   cmd                true if the command key was pressed
--   keycode            numeric virtual keycode (e.g., 48)
--   appname            the frontmost application (e.g., Terminal)
--
-- The order of the modifier keys in key-str-eq is always:
--   shift control alt cmd fn, separated by a hyphen ("-").

function swap_keys(t)
   -- for i,v in pairs(t) do print(i,v) end
   -- print(t.appname)
   if set_contains(global_excludes, t.key_str_seq) then
      return false
   end
   if not apps[t.appname] then
      return false
   end
   local excludes = apps[t.appname]["exclude"]
   if (excludes ~= nil and set_contains(excludes, t.key_str_seq)) then
      -- print("exluding: ", t.key_str_seq)
      return false
   end
   return true
end
```

**Comment by ghost** [comment]
I have some time to look into this now.

The name is "IntelliJ IDEA". Can you give me an example that doesn't work for you?

**Comment by jmcmichael** [comment]
"IntelliJ IDEA" works fine for the release of IntelliJ that uses Apple's built-in JRE. However, if you download any of the pre-release versions that bundle Oracle's latest JRE (e.g. [ideaIU-140.2493.5-custom-jdk-bundled.dmg](http://download.jetbrains.com/idea/ideaIU-140.2493.5-custom-jdk-bundled.dmg), or force the release version to use Oracle's JRE, cmd-key-happy ceases to work with any of the name variations I've tried that you can see in the config file above.

**Comment by frobware** [comment]
Let me try based on your link. Once I have it installed should I change the preferences to use Emacs keybindings -- or, what's the symptom I should be looking for?

**Comment by ghost** [comment]
Pretty sure the app name is "IntelliJ IDEA":

aim@imac:~/cmd-key-happy/cpp
: ./cmd-key-happy -l | grep Intelli
IntelliJ IDEA

This -l option is on the dev branch - some of which is not currently pushed.

**Comment by ghost** [comment]
Can we hone in on what doesn't work for you?  I have installed the pre-release based on your link. I have used your .lua file and, with Emacs keybindings set in IntelliJ, I can 'cmd-f', 'cmd-b' in a source file within IntelliJ. Which bit am I missing?

**Comment by jmcmichael** [comment]
@frobware, @andymcd yeah verifying cmd-f, cmd-b with emacs keybindings in IntelliJ is a good test case. That doesn't work for me, or at least didn't when I tried it a couple weeks ago.

I'll reinstall the EAP build of IntelliJ tonight and restart everything to see if I am still experiencing the same behavior. Thank you for looking into this!

I do recall a couple years ago, after doing a major upgrade, that cmd-key happy didn't appear to work but then magically started working a couple days later, could be a startup issue maybe?

**Comment by ghost** [comment]
@jmcmichael - any joy?

I have "cmd-f" and "cmd-b" doing the right thing in IntelliJ.

**Comment by jmcmichael** [comment]
Hey guys, sorry I've been swamped and haven't wanted to meddle with my development setup for the past week but should be able to take some time in the next few days to get back to troubleshooting on this. I want to remove/reinstall the latest versions of everything just to make sure I'm starting from a clean slate.

**Comment by jmcmichael** [comment]
OK, I've had a chance to update cmd-key-happy to the latest and do some more exploring with the IntelliJ IDEA EAP release.

It's still not working properly, but I've discovered that cmd-key-happy is halfway there. It's managed to swap the command key with the option key, but the command key doesn't appear be switched out, or indeed to do anything at all. I have no idea why it seems to be working for @andymcd but not me.

To reproduce:
1. Download and install the latest IDEA EAP (currently it's [the Feb 20th release](http://download.jetbrains.com/idea/ideaIU-139.1408.1-jdk-bundled.dmg))
2. Ensure that cmd-key-happy is looking for IntelliJ by adding it to your cmd-key-happy rcfile. I've got the following, and I'm not sure which one is working:

``` lua
   ["IntelliJ IDEA"] = { exclude = {} },
   ["IntelliJ IDEA-EAP"] = { exclude = {} },
   ["IntelliJ IDEA EAP"] = { exclude = {} },
```
1. Fire up Intellij, open up Preferences and find the Keymap section.
2. There's a 'Find Actions by Shortcut' helper to the right next to the command search box, it's handy to use for testing b/c you get immediate feedback on the keys and modifiers being pressed. Click that.
3. Press option-f, note that &#8984;F is shown in the 'First Stroke' box. Press cmd-f, note that the First Stroke box remains unchanged, as if IntelliJ hasn't detected either the option or the f key being pressed.

**Comment by ghost** [comment]
I cannot reproduce this.

I just tried the following:
1. pkill cmd-key-happy
2. make uninstall
3. remove both cmd-key-happy and terminal from authorised apps in system prefs -> security...
4. make && make install && make install-plist

cmd-key-happy should now be running, popping up the security access, which I granted.
1. cmd-key-happy-restart

I have the following setting in my .lua file:

```
["IntelliJ IDEA"] = { exclude = Set { "cmd-`"} },
```

And then I tried your "Find Actions by Shortcut". For me, if strike "cmd-f" I get "alt-f", and vice-versa.

**Comment by andymcd** [comment]
I cannot reproduce this.

I just tried the following:

1. pkill cmd-key-happy
2. make uninstall
3. remove both cmd-key-happy and terminal from authorised apps in system prefs -> security...
4. make && make install && make install-plist

cmd-key-happy should now be running, popping up the security access, which I granted.

5. cmd-key-happy-restart

I have the following setting in my .lua file:

    ["IntelliJ IDEA"] = { exclude = Set { "cmd-`"} },

And then I tried your "Find Actions by Shortcut". For me, if strike "cmd-f" I get "alt-f", and vice-versa.

**Comment by andymcd** [comment]
I cannot reproduce this.

I just tried the following:

1. pkill cmd-key-happy
2. make uninstall
3. remove both cmd-key-happy and terminal from authorised apps in system prefs -> security...
4. make && make install && make install-plist

cmd-key-happy should now be running, popping up the security access, which I granted.

5. cmd-key-happy-restart

I have the following setting in my .lua file:

    ["IntelliJ IDEA"] = { exclude = Set { "cmd-`"} },

And then I tried your "Find Actions by Shortcut". For me, if strike "cmd-f" I get "alt-f", and vice-versa.

**Comment by ghost** [comment]
If you do all the steps I just highlighted, you could also try:
1. pkill cmd-key-happy
2. /usr/local/bin/cmd-key-happy

Grant access to "Terminal" -- the dialog that pops up should be "Terminal", not "cmd-key-happy" would like to use u...

Then try your IntelliJ scenario. This way would allow cmd-key-happy to run in the foreground.

**Comment by ghost** [comment]
You could also try all of this in a new (temporary) user account to ensure nothing is being cached, etc. Perhaps even using the 'Guest' account.

**Comment by jmcmichael** [comment]
OK, I will work on pinpointing the problem and post a new issue when I do. Thanks very much for your time on this.
