### ISSUE TITLE
Problem on Yosemite

### ISSUE THREAD

**Issue by joelruns** [frobware/cmd-key-happy#20]
This does not work on Yosemite for me. Followed MakeFile instructions. Using example Lua file. Not sure what Error 3 is in plist part. I tried activating and deactivating use Option as Meta. Any ideas?

$ make output
cc -Ilua-5.2.1/src -MMD -Wpointer-arith -Werror -Wall -Wextra -W -Wunused -Wno-unused-parameter -Wno-unused-function -Wuninitialized -std=c99 -O3 -c -o cmd-key-happy.o cmd-key-happy.m
cc -Ilua-5.2.1/src -O3 -c -o lua-5.2.1.o lua-5.2.1.c
cc -g -o cmd-key-happy cmd-key-happy.o lua-5.2.1.o -framework Foundation -framework AppKit -framework Carbon

$ sudo make install
/usr/bin/install -d /usr/local/bin
/usr/bin/install -m 555 cmd-key-happy /usr/local/bin
/usr/bin/install -m 555 cmd-key-happy-restart.sh /usr/local/bin/cmd-key-happy-restart

$ make install-rcfile
cp example-rcfile.lua ~/.cmd-key-happy.lua

$ make install-plist
mkdir -p /Users/Joel/Library/LaunchAgents
launchctl stop com.frobware.cmd-key-happy
make: [install-plist] Error 3 (ignored)
launchctl unload /Users/Joel/Library/LaunchAgents/com.frobware.cmd-key-happy.plist
/Users/Joel/Library/LaunchAgents/com.frobware.cmd-key-happy.plist: No such file or directory
rm -f /Users/Joel/Library/LaunchAgents/com.frobware.cmd-key-happy.plist
sed -e 's~%INSTALL_ROOT~/usr/local~' com.frobware.cmd-key-happy.plist > /Users/Joel/Library/LaunchAgents/com.frobware.cmd-key-happy.plist
chmod 644 /Users/Joel/Library/LaunchAgents/com.frobware.cmd-key-happy.plist
launchctl load -S Aqua /Users/Joel/Library/LaunchAgents/com.frobware.cmd-key-happy.plist
launchctl start com.frobware.cmd-key-happy

I set my permissions as specified.

$ cmd-key-happy-restart

**Comment by ghost** [comment]
The "Error 3" is probably a first install issue - there was nothing to do because cmd-key-happy wasn't already running.  You have to also open "System Preferences", "Security & Privacy", look in the "Accessibility" section and enable "cmd-key-happy". After that, run "cmd-key-happy-restart".

**Comment by joelruns** [comment]
Yes I have followed those instructions completely. Here's a photo of my System Preferences to show. I have checked Activity Monitor and it shows "cmd-key-happy" is running but if I open a new Terminal.app and type Command-F for example, I still get find.
![screen shot 2015-02-26 at 4 11 44 pm](https://cloud.githubusercontent.com/assets/5619611/6402001/4a0374c2-bdd2-11e4-9c49-0d56713200b5.png)

**Comment by ghost** [comment]
The sample file explicitly excludes "cmd-v". cmd-key-happy will swap cmd for alt except where specified. that's the purpose of the "excludes = { ... }" section. Try removing cmd-v - and don't forget to run cmd-key-happy-restart for each file change.

**Comment by joelruns** [comment]
Sorry I meant Command-F. I have also tested with Command-S and other key combinations not in excludes and Terminal.app displays normal behavior. Below is my .cmd-key-happy.lua file if it helps.

function Set(t)
   local s = {}
   for _,v in pairs(t) do s[v] = true end
   return s
end

function set_contains(t, e)
   return t[e]
end

-- The set of global shortcuts we don't want to swap cmd/alt.

global_excludes = Set{ "shift-cmd-tab",
               "cmd-tab" }

-- The set of apps we want to consider swapping keys for, with some
-- notable exclusions. The exclusion means that a "cmd-c" will do the
-- normal OS Terminal behaviour. If you omit items then you would
-- have to use "alt-c" to close a terminal window.

apps = {
   Terminal = { exclude = Set{ "shift-cmd-[",
                               "shift-cmd-]",
                               "cmd-c",
                               "cmd-v",
                               "cmd-1",
                               "cmd-2",
                               "cmd-3",
                               "cmd-t",
                               "cmd-n",
                               "cmd-`",
             } },
   Eclipse  = { exclude = {} },
   Xcode    = { exclude = {} },
   TextMate = { exclude = Set { "cmd-1",
                "cmd-2",
                "cmd-3",
                "cmd-4",
                "cmd-t" ,
                "cmd-fn-right",
                "cmd-fn-left",
              } },
   ["NX Player for OS X"] = { exclude = Set{} },
   ["Parallels Desktop"] = {},
}

debug = false

dbgprintf = function(s,...)
   if debug then io.write(s:format(...)) end
end

-- Return true to swap cmd/alt, otherwise false.

-- This function is passed a table comprising the following keys:
--   key_str_seq    key sequence (e.g., "shift-cmd-e")
--   alt        true if the alt key was pressed
--   fn                 true if the fn key was pressed
--   control            true if the control key was pressed
--   shift              true if the shift key was pressed
--   cmd                true if the command key was pressed
--   keycode        numeric virtual keycode (e.g., 48)
--   appname            the frontmost application (e.g., Terminal)

-- The order of the modifier keys in key_str_eq is always:
--   shift control alt cmd fn, separated by a hyphen ("-").

function swap_keys(t)
   -- for i,v in pairs(t) do print(i,v) end
   -- print(t.appname)
   if set_contains(global_excludes, t.key_str_seq) then
      return false
   end
   if not apps[t.appname] then
      return false
   end
   local excludes = apps[t.appname]["exclude"]
   if (excludes ~= nil and set_contains(excludes, t.key_str_seq)) then
      dbgprintf("-- %s: \"%s\", explicitly ignored\n", t.appname, t.key_str_seq)
      return false
   end
   s, n = t.key_str_seq:gsub("cmd", "alt")

**Comment by ghost** [comment]
Could you uncomment the two lines towards the top of the swap_keys function and then run cmd-key-happy in the foreground.

 $ pkill cmd-key-happy
 $ /usr/local/bin/cmd-key-happy

This will at least help us see if the install went OK as you should get the app name printed together with all the parameters to the function.

**Comment by joelruns** [comment]
Asks me to set permission for Terminal. I set allow. Nothing gets printed unless I use a Command key combo in application other than Terminal. For example Command-F in Safari prints this. Tried adding Safari to list and key mapping works. For some reason not working for Terminal alone.

key_str_seq cmd-f
cmd true
appname Safari
control false
keycode 3
Safari
shift   false
fn  false
alt false

**Comment by ghost** [comment]
Could you try the following:

 $ make uninstall

Go to "Security & Privacy" preferences, then "Privacy". From there remove entries for 'cmd-key-happy' and 'Terminal'.

Back in your shell:

 $ make install
 $ make install-plist

That should pop-up a dialog, click "Open System Preferences" in that dialog and grant "cmd-key-happy" access. It should be listed there, but not checked.

 $ cmd-key-happy-restart
 $ pgrep cmd-key-happy

And see if that works. I just tried that sequence - it's important after the uninstall steps that "cmd-key-happy" is not listed in the Privacy list.

**Comment by joelruns** [comment]
I followed exactly and made sure that cmd-key-happy was removed from the Privacy list after uninstall. Then I did the reinstall and ran the two commands. Returns "23656" but still does not work.

**Comment by ghost** [comment]
I'm at a loss...

When you did the 'make install-plist' step, did you see the dialog pop up?

**Comment by joelruns** [comment]
Yes indeed I did. Let me screen cap the whole process one second.

**Comment by ghost** [comment]
Reboot? (bleh!)

**Comment by joelruns** [comment]
A couple things I noticed. Weirdly it works for Safari but not Terminal. T-T

![screen shot 2015-02-26 at 6 06 29 pm](https://cloud.githubusercontent.com/assets/5619611/6404196/7fc30404-bde3-11e4-999a-ff9bb5b93a15.png)
![screen shot 2015-02-26 at 6 06 02 pm](https://cloud.githubusercontent.com/assets/5619611/6404198/8593097e-bde3-11e4-8063-a765ea45256a.png)
![screen shot 2015-02-26 at 6 07 27 pm](https://cloud.githubusercontent.com/assets/5619611/6404200/898f466e-bde3-11e4-8571-e9fa40280cbf.png)
![screen shot 2015-02-26 at 6 12 07 pm](https://cloud.githubusercontent.com/assets/5619611/6404201/8c7ec598-bde3-11e4-8105-4e268fb76ccf.png)
![screen shot 2015-02-26 at 6 09 18 pm](https://cloud.githubusercontent.com/assets/5619611/6404204/8f6ea188-bde3-11e4-8513-6f2719ad0ad8.png)
![screen shot 2015-02-26 at 6 12 37 pm](https://cloud.githubusercontent.com/assets/5619611/6404205/9237c840-bde3-11e4-9864-43ce49fd6b4c.png)
![screen shot 2015-02-26 at 6 12 43 pm](https://cloud.githubusercontent.com/assets/5619611/6404206/94dc5994-bde3-11e4-99ec-a5b022655443.png)

**Comment by ghost** [comment]
Thanks for all the detail. And I like your separator in the terminal windows. :) 

Do you have "Use Option as Meta Key" checked in your Terminal profile?

**Comment by ghost** [comment]
I know (quite some time ago) somebody had similar problems with Terminal - though not exactly sure he was trying this in any other app but we ended up deleting his Terminal preferences:

 $ cp ~/Library/Preferences/com.apple.Terminal.plist ~/Terminal-Prefs.orig
 $ rm ~/Library/Preferences/com.apple.Terminal.plist

quit and start Terminal, add back "Use Option as Meta". Really don't understand what's going wrong here.

One other thing: what do you set your terminal type to?

  $ echo $TERM

**Comment by joelruns** [comment]
Haha thanks! I have tried with both options for my profile and done a restart for both changes. Still not working.

I will try the preferences in a second.

$ echo $TERM
xterm-16color

**Comment by ghost** [comment]
I have 'xterm-256color'. I would be genuinely shocked if that made any difference...

**Comment by ghost** [comment]
And... going back to basics a bit... if it works for Safari then perhaps something else is stealing the 'Event Tap' for Terminal. What does "Spectacle" do? I see that listed in your accessibility list.

**Comment by joelruns** [comment]
Hmm yeah removing the preferences file did nothing. It might actually be Spectacle. I use that to map window size changing. Let me try removing that for a bit.

**Comment by joelruns** [comment]
Darn still nothing with Spectacle removed.

**Comment by ghost** [comment]
I need to head to bed... (just gone midnight here).

I have a dev branch which you could try...

**Comment by joelruns** [comment]
Ah thanks for the help so far. Yes if you could let me know how to checkout that branch.

**Comment by ghost** [comment]
git clone http://github.com/andymcd/cmd-key-happy -b dev
cd cmd-key-happy/cpp
make
make local-lua-install
./lua2rc ~/.cmd-key-happy.lua > ~/.cmd-key-happy.rc
make uninstall
make install
make install-plist
cmd-key-happy-restart 

Good luck!

**Comment by joelruns** [comment]
Solved! There was a permissions issue with Terminal key events. If you click Terminal in top menu options it gives a drop down and there is an option called "Secure Keyboard Entry" that completely blocks some key events. Unchecking it lets it work otherwise cmd-key-happy must be run as root. Good game.

**Comment by wew036** [comment]
I did not have "Secure Keyboard Entry" in my terminal, and the master also does not work for me.  However, the dev patch works for me.  Thanks!
