### ISSUE TITLE
Pledgie broken?

### ISSUE THREAD

**Issue by mgalgs** [frobware/cmd-key-happy#22]
Can't tell if it's a pledgie problem or if it's a frob@pledgie problem...

![image](https://cloud.githubusercontent.com/assets/152014/15337938/b0bb35b4-1c32-11e6-81b0-68987e09e7b6.png)

**Comment by frobware** [comment]
I removed this. If you feel as though you would still like to donate then please choose a charity of your choice. Many thanks for trying in the first place. +1
